spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthdb?useSSL=false
    username: root
    password: tlstmdgh24)!
  jpa:
    database: mysql
    #InnoDB?? -> transaction? ???? db
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #???? ???? ???? ????? ???? jpa? ?? ????.
    generate-ddl: true
    hibernate:
      ddl-auto: create #?? create ??? ?? ??? ?????? ???? ?????? -> ??? ??? ???? ??? update, validate? ???? ??????.
    show-sql: true

jwt:
  # 32?? ???? ?? ??? ??????.
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vub2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbg==
  expiration: 3000 # ?? ?? ??? ??... refresh token? ?? ?? ?? ?? ?... ?? test ???? ? ?? ???!